### ISSUE TITLE
Yaks to shave

### ISSUE THREAD

**Issue by nybblr** [radishmouse/chattrbox#1]
If you use an arrow function instead, you can skip the `self = this`:
https://github.com/radishmouse/chattrbox/blob/master/app/scripts/src/dom.js#L17-L18

You can take advantage of the new object literal syntax, e.g. `export default { UserStore, MessageStore }`:
https://github.com/radishmouse/chattrbox/blob/master/app/scripts/src/storage.js#L46-L49

That is all! I love how you've ES6-ified stuff into DOM/Store/etc.

**Comment by radishmouse** [comment]
Fixed! ...in some unspecified commit that I was working on around 3am last night...
To be merged into master shortly.
